ARG VERSION
# almalinux 9 ver use chesthunamm if futurer lo 10 or any othervresion kabalane mali file ki 
#vachi edit cheyyali push chesi pull cheyyali. so ala chyyakunda VERSION var istham if vers valu ivvakapothe default 9 teesukuntundhi
FROM almalinux:${VERSION:-9} 